# Generated by Django 4.0.3 on 2022-05-11 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_plot_alter_watering_options_alter_watering_water_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='date_planted',
            field=models.DateField(default=datetime.date(2022, 5, 11)),
        ),
    ]
