# Generated by Django 4.0.3 on 2022-05-11 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_seed_date_planted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='date_planted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
